# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solving Generalized LASSO with fixed \eqn{\lambda = 1}
NULL

genlassoRcpp <- function(Y, W, m, eta1, eta2, a, rho, max_iter, eps, truncate) {
    .Call('_wfla_genlassoRcpp', PACKAGE = 'wfla', Y, W, m, eta1, eta2, a, rho, max_iter, eps, truncate)
}

